modLoader="javafml" #mandatory
loaderVersion="[32,)"
license="MIT"
issueTrackerURL="https://github.com/Boundarybreaker/Skychunk/issues"
[[mods]]
modId="skychunk"
version="${file.jarVersion}"
displayName="Ears"
displayURL="https://www.curseforge.com/minecraft/mc-mods/skychunk"
logoFile="assets/skychunk/icon.png"
authors="Boundarybreaker"
description="Removes 95% of chunks from the world. Mod request from ThatNEET_"